// <auto-generated />
using System;
using ChargingControlSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChargingControlSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251123133946_AddBootNotificationFields")]
    partial class AddBootNotificationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.AuthorizationMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuthorizationMethods");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.BillingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("BillingAccounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddd1111-1111-1111-1111-111111111111"),
                            AccountName = "Hauptkonto ChargingControl GmbH",
                            CreatedAt = new DateTime(2025, 10, 24, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(5119),
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.BillingTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChargingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BillingAccountId");

                    b.HasIndex("ChargingSessionId");

                    b.ToTable("BillingTransactions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingPark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ChargingParks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Address = "Hauptstraße 123",
                            City = "München",
                            Country = "Deutschland",
                            CreatedAt = new DateTime(2025, 11, 3, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4902),
                            Description = "Zentraler Parkplatz am Hauptgebäude",
                            IsActive = true,
                            Latitude = 48.1351m,
                            Longitude = 11.5820m,
                            Name = "Hauptgebäude Parkplatz",
                            PostalCode = "80331",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Address = "Friedrichstraße 45",
                            City = "Berlin",
                            Country = "Deutschland",
                            CreatedAt = new DateTime(2025, 11, 8, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4907),
                            Description = "Ladepark an der Berliner Niederlassung",
                            IsActive = true,
                            Latitude = 52.5200m,
                            Longitude = 13.4050m,
                            Name = "Außenstelle Berlin",
                            PostalCode = "10117",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CertificateChain")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConnectorFormat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EvseId")
                        .HasColumnType("int");

                    b.Property<string>("EvseIdExternal")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastStatusChange")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxCurrent")
                        .HasColumnType("int");

                    b.Property<int>("MaxPower")
                        .HasColumnType("int");

                    b.Property<int>("MaxVoltage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhysicalReference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PowerType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PublicKey")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("SupportsRemoteStartStop")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsReservation")
                        .HasColumnType("bit");

                    b.Property<bool>("SupportsSmartCharging")
                        .HasColumnType("bit");

                    b.Property<string>("TariffInfo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationId");

                    b.ToTable("ChargingPoints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            ChargingStationId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ConnectorFormat = "SOCKET",
                            ConnectorType = "CCS",
                            CreatedAt = new DateTime(2025, 11, 3, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4991),
                            EvseId = 1,
                            IsActive = true,
                            MaxCurrent = 200,
                            MaxPower = 150,
                            MaxVoltage = 800,
                            Name = "Ladepunkt 1",
                            PowerType = "DC",
                            Status = 0,
                            SupportsRemoteStartStop = true,
                            SupportsReservation = false,
                            SupportsSmartCharging = true
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            ChargingStationId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ConnectorFormat = "SOCKET",
                            ConnectorType = "CCS",
                            CreatedAt = new DateTime(2025, 11, 3, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4994),
                            EvseId = 2,
                            IsActive = true,
                            MaxCurrent = 200,
                            MaxPower = 150,
                            MaxVoltage = 800,
                            Name = "Ladepunkt 2",
                            PowerType = "DC",
                            Status = 0,
                            SupportsRemoteStartStop = true,
                            SupportsReservation = false,
                            SupportsSmartCharging = true
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorizationMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ChargingCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChargingPointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EnergyDelivered")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("OcppTransactionId")
                        .HasColumnType("int");

                    b.Property<Guid?>("QrCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationMethodId");

                    b.HasIndex("ChargingPointId");

                    b.HasIndex("QrCodeId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ChargingSessions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChargeBoxId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ChargingParkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Iccid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Imsi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<int>("MaxPower")
                        .HasColumnType("int");

                    b.Property<string>("MeterSerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MeterType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumberOfConnectors")
                        .HasColumnType("int");

                    b.Property<string>("OcppEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OcppPassword")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OcppProtocol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChargingParkId");

                    b.HasIndex("StationId")
                        .IsUnique();

                    b.ToTable("ChargingStations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ChargingParkId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 11, 3, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4946),
                            IsActive = true,
                            LastHeartbeat = new DateTime(2025, 11, 23, 13, 34, 46, 275, DateTimeKind.Utc).AddTicks(4947),
                            Latitude = 48.1351m,
                            Longitude = 11.5820m,
                            MaxPower = 150,
                            Model = "Sicharge CC",
                            Name = "CCS Schnellladesäule 1",
                            NumberOfConnectors = 2,
                            StationId = "CCS-001",
                            Status = 0,
                            Type = 1,
                            Vendor = "Siemens"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            ChargingParkId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 11, 5, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4952),
                            IsActive = true,
                            LastHeartbeat = new DateTime(2025, 11, 23, 13, 36, 46, 275, DateTimeKind.Utc).AddTicks(4953),
                            Latitude = 48.1352m,
                            Longitude = 11.5821m,
                            MaxPower = 22,
                            Model = "Terra AC",
                            Name = "AC Standardladesäule 1",
                            NumberOfConnectors = 2,
                            StationId = "AC-001",
                            Status = 0,
                            Type = 0,
                            Vendor = "ABB"
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStationGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChargingParkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChargingParkId");

                    b.HasIndex("TenantId");

                    b.ToTable("ChargingStationGroups");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStationGroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChargingStationGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationGroupId");

                    b.HasIndex("ChargingStationId");

                    b.ToTable("ChargingStationGroupMemberships");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.GroupPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserGroupId", "PermissionId")
                        .IsUnique();

                    b.ToTable("GroupPermissions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Action = "view",
                            Description = "View users",
                            Name = "users.view",
                            Resource = "users"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Action = "create",
                            Description = "Create users",
                            Name = "users.create",
                            Resource = "users"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Action = "edit",
                            Description = "Edit users",
                            Name = "users.edit",
                            Resource = "users"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Action = "delete",
                            Description = "Delete users",
                            Name = "users.delete",
                            Resource = "users"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Action = "view",
                            Description = "View vehicles",
                            Name = "vehicles.view",
                            Resource = "vehicles"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Action = "create",
                            Description = "Create vehicles",
                            Name = "vehicles.create",
                            Resource = "vehicles"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Action = "edit",
                            Description = "Edit vehicles",
                            Name = "vehicles.edit",
                            Resource = "vehicles"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Action = "assign",
                            Description = "Assign vehicles",
                            Name = "vehicles.assign",
                            Resource = "vehicles"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Action = "view",
                            Description = "View charging infrastructure",
                            Name = "charging.view",
                            Resource = "charging"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000a"),
                            Action = "manage",
                            Description = "Manage charging infrastructure",
                            Name = "charging.manage",
                            Resource = "charging"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000b"),
                            Action = "view",
                            Description = "View billing information",
                            Name = "billing.view",
                            Resource = "billing"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000c"),
                            Action = "manage",
                            Description = "Manage billing",
                            Name = "billing.manage",
                            Resource = "billing"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000d"),
                            Action = "view",
                            Description = "View QR codes",
                            Name = "qrcodes.view",
                            Resource = "qrcodes"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000e"),
                            Action = "create",
                            Description = "Create QR codes",
                            Name = "qrcodes.create",
                            Resource = "qrcodes"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000f"),
                            Action = "manage",
                            Description = "Manage QR codes",
                            Name = "qrcodes.manage",
                            Resource = "qrcodes"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Action = "view",
                            Description = "View tariffs",
                            Name = "tariffs.view",
                            Resource = "tariffs"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Action = "create",
                            Description = "Create tariffs",
                            Name = "tariffs.create",
                            Resource = "tariffs"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Action = "edit",
                            Description = "Edit tariffs",
                            Name = "tariffs.edit",
                            Resource = "tariffs"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Action = "delete",
                            Description = "Delete tariffs",
                            Name = "tariffs.delete",
                            Resource = "tariffs"
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.QrCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChargingParkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentUses")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChargingParkId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("QrCodes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeee2222-2222-2222-2222-222222222222"),
                            ChargingParkId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Code = "CC-PARK-001",
                            CreatedAt = new DateTime(2025, 11, 13, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(5150),
                            CurrentUses = 0,
                            Description = "Einladung zum Hauptparkplatz",
                            ExpiresAt = new DateTime(2026, 11, 23, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(5148),
                            IsActive = true,
                            MaxUses = 100,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Type = 0
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Tariffs");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.TariffComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DaysOfWeek")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("GracePeriodMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaximumCharge")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<decimal?>("MinimumCharge")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<int?>("StepSize")
                        .HasColumnType("int");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TimeEnd")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TimeStart")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TariffId");

                    b.ToTable("TariffComponents");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Theme")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentTenantId");

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Musterstraße 123",
                            City = "Berlin",
                            Country = "Deutschland",
                            CreatedAt = new DateTime(2025, 10, 24, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4730),
                            Description = "Hauptunternehmen für Lade-Management",
                            Email = "info@chargingcontrol.de",
                            IsActive = true,
                            Name = "ChargingControl GmbH",
                            Phone = "+49 30 12345678",
                            PostalCode = "10115",
                            Subdomain = "chargingcontrol",
                            TaxId = "DE123456789",
                            Theme = 0,
                            Website = "https://www.chargingcontrol.de"
                        },
                        new
                        {
                            Id = new Guid("aaaabbbb-1111-2222-3333-444444444444"),
                            Address = "Acme Straße 456",
                            City = "München",
                            Country = "Deutschland",
                            CreatedAt = new DateTime(2025, 10, 29, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4740),
                            Description = "Sub-Tenant für Acme Corporation",
                            Email = "info@acme.de",
                            IsActive = true,
                            Name = "Acme GmbH",
                            ParentTenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phone = "+49 89 98765432",
                            PostalCode = "80331",
                            Subdomain = "acme",
                            TaxId = "DE987654321",
                            Theme = 0,
                            Website = "https://www.acme.de"
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 10, 24, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4822),
                            Email = "admin@chargingcontrol.com",
                            FirstName = "Admin",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            LastLoginAt = new DateTime(2025, 11, 22, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4822),
                            LastName = "User",
                            PasswordHash = "$2a$11$QUxBZq94RgWvH09M.ER7EuF6Ju3mP45b9cEXAS99Iz09cAfKEZUeW",
                            Role = 1,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaabbbb-2222-3333-4444-555555555555"),
                            CreatedAt = new DateTime(2025, 10, 29, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4829),
                            Email = "admin@acme.com",
                            FirstName = "John",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            LastLoginAt = new DateTime(2025, 11, 21, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4830),
                            LastName = "Doe",
                            PasswordHash = "$2a$11$QUxBZq94RgWvH09M.ER7EuF6Ju3mP45b9cEXAS99Iz09cAfKEZUeW",
                            Role = 1,
                            TenantId = new Guid("aaaabbbb-1111-2222-3333-444444444444")
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InviteToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("InviteTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 10, 24, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4784),
                            Description = "Vollständige Administrator-Rechte",
                            IsActive = true,
                            Name = "Administratoren",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaabbbb-3333-4444-5555-666666666666"),
                            CreatedAt = new DateTime(2025, 10, 29, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4786),
                            Description = "Administrator-Rechte für Acme",
                            IsActive = true,
                            Name = "Acme Administratoren",
                            TenantId = new Guid("aaaabbbb-1111-2222-3333-444444444444")
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroupChargingStationGroupPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChargingStationGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationGroupId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("UserGroupChargingStationGroupPermissions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserGroupId");

                    b.HasIndex("UserId", "UserGroupId")
                        .IsUnique();

                    b.ToTable("UserGroupMemberships");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccccdddd-1111-2222-3333-444444444444"),
                            AssignedAt = new DateTime(2025, 10, 24, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4863),
                            UserGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("ccccdddd-2222-3333-4444-555555555555"),
                            AssignedAt = new DateTime(2025, 10, 29, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(4866),
                            UserGroupId = new Guid("aaaabbbb-3333-4444-5555-666666666666"),
                            UserId = new Guid("aaaabbbb-2222-3333-4444-555555555555")
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroupTariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TariffId");

                    b.HasIndex("UserGroupId", "TariffId")
                        .IsUnique();

                    b.ToTable("UserGroupTariffs");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QrCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RfidTag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LicensePlate")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Color = "Pearl White",
                            CreatedAt = new DateTime(2025, 10, 29, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(5029),
                            IsActive = true,
                            LicensePlate = "M-CC 1234",
                            Make = "Tesla",
                            Model = "Model 3",
                            Notes = "Poolfahrzeug für Geschäftsreisen",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Type = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Color = "Mineral White",
                            CreatedAt = new DateTime(2025, 11, 3, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(5033),
                            IsActive = true,
                            LicensePlate = "M-CC 5678",
                            Make = "BMW",
                            Model = "i3",
                            Notes = "Dienstwagen für den Vertrieb",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Type = 1,
                            Year = 2022
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.VehicleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignmentType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleAssignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccc0000-0000-0000-0000-000000000000"),
                            AssignedAt = new DateTime(2025, 11, 16, 13, 39, 46, 275, DateTimeKind.Utc).AddTicks(5058),
                            AssignmentType = 1,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            VehicleId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.AuthorizationMethod", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.User", "User")
                        .WithMany("AuthorizationMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.BillingAccount", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany("BillingAccounts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.BillingTransaction", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.BillingAccount", "BillingAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingSession", "ChargingSession")
                        .WithMany()
                        .HasForeignKey("ChargingSessionId");

                    b.Navigation("BillingAccount");

                    b.Navigation("ChargingSession");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingPark", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany("ChargingParks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingPoint", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingStation", "ChargingStation")
                        .WithMany("ChargingPoints")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingStation");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingSession", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.AuthorizationMethod", "AuthorizationMethod")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("AuthorizationMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingPoint", "ChargingPoint")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("ChargingPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.QrCode", "QrCode")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("QrCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.User", "User")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChargingControlSystem.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AuthorizationMethod");

                    b.Navigation("ChargingPoint");

                    b.Navigation("QrCode");

                    b.Navigation("Tenant");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStation", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingPark", "ChargingPark")
                        .WithMany("ChargingStations")
                        .HasForeignKey("ChargingParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingPark");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStationGroup", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingPark", "ChargingPark")
                        .WithMany()
                        .HasForeignKey("ChargingParkId");

                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingPark");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStationGroupMembership", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingStationGroup", "ChargingStationGroup")
                        .WithMany("StationMemberships")
                        .HasForeignKey("ChargingStationGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingStation", "ChargingStation")
                        .WithMany()
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChargingStation");

                    b.Navigation("ChargingStationGroup");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.GroupPermission", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Permission", "Permission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.UserGroup", "UserGroup")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.QrCode", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingPark", "ChargingPark")
                        .WithMany("QrCodes")
                        .HasForeignKey("ChargingParkId");

                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.User", "User")
                        .WithMany("QrCodes")
                        .HasForeignKey("UserId");

                    b.Navigation("ChargingPark");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Tariff", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.TariffComponent", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tariff", "Tariff")
                        .WithMany("Components")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Tenant", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "ParentTenant")
                        .WithMany("SubTenants")
                        .HasForeignKey("ParentTenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.User", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroup", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.User", null)
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroupChargingStationGroupPermission", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingStationGroup", "ChargingStationGroup")
                        .WithMany("UserGroupPermissions")
                        .HasForeignKey("ChargingStationGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.UserGroup", "UserGroup")
                        .WithMany("ChargingStationGroupPermissions")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChargingStationGroup");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroupMembership", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.UserGroup", "UserGroup")
                        .WithMany("UserGroupMemberships")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.User", "User")
                        .WithMany("UserGroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroupTariff", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tariff", "Tariff")
                        .WithMany("UserGroupTariffs")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.UserGroup", "UserGroup")
                        .WithMany()
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tariff");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Vehicle", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany("Vehicles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.VehicleAssignment", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.User", "User")
                        .WithMany("VehicleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleAssignments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.AuthorizationMethod", b =>
                {
                    b.Navigation("ChargingSessions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.BillingAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingPark", b =>
                {
                    b.Navigation("ChargingStations");

                    b.Navigation("QrCodes");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingPoint", b =>
                {
                    b.Navigation("ChargingSessions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStation", b =>
                {
                    b.Navigation("ChargingPoints");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStationGroup", b =>
                {
                    b.Navigation("StationMemberships");

                    b.Navigation("UserGroupPermissions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Permission", b =>
                {
                    b.Navigation("GroupPermissions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.QrCode", b =>
                {
                    b.Navigation("ChargingSessions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Tariff", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("UserGroupTariffs");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Tenant", b =>
                {
                    b.Navigation("BillingAccounts");

                    b.Navigation("ChargingParks");

                    b.Navigation("ChargingSessions");

                    b.Navigation("SubTenants");

                    b.Navigation("Users");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.User", b =>
                {
                    b.Navigation("AuthorizationMethods");

                    b.Navigation("ChargingSessions");

                    b.Navigation("QrCodes");

                    b.Navigation("UserGroupMemberships");

                    b.Navigation("UserGroups");

                    b.Navigation("VehicleAssignments");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroup", b =>
                {
                    b.Navigation("ChargingStationGroupPermissions");

                    b.Navigation("GroupPermissions");

                    b.Navigation("UserGroupMemberships");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Vehicle", b =>
                {
                    b.Navigation("ChargingSessions");

                    b.Navigation("VehicleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
