// <auto-generated />
using System;
using ChargingControlSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChargingControlSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023145625_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.AuthorizationMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuthorizationMethods");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.BillingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("BillingAccounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddd1111-1111-1111-1111-111111111111"),
                            AccountName = "Hauptkonto ChargingControl GmbH",
                            CreatedAt = new DateTime(2025, 9, 23, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8515),
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.BillingTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChargingSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BillingAccountId");

                    b.HasIndex("ChargingSessionId");

                    b.ToTable("BillingTransactions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingConnector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxCurrent")
                        .HasColumnType("int");

                    b.Property<int>("MaxPower")
                        .HasColumnType("int");

                    b.Property<int>("MaxVoltage")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationId");

                    b.ToTable("ChargingConnectors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            ChargingStationId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ConnectorId = 1,
                            ConnectorType = "CCS",
                            CreatedAt = new DateTime(2025, 10, 3, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8408),
                            MaxCurrent = 200,
                            MaxPower = 0,
                            MaxVoltage = 800,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            ChargingStationId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ConnectorId = 2,
                            ConnectorType = "CCS",
                            CreatedAt = new DateTime(2025, 10, 3, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8411),
                            MaxCurrent = 200,
                            MaxPower = 0,
                            MaxVoltage = 800,
                            Status = 0
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingPark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ChargingParks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Address = "Hauptstraße 123",
                            City = "München",
                            Country = "Deutschland",
                            CreatedAt = new DateTime(2025, 10, 3, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8343),
                            Description = "Zentraler Parkplatz am Hauptgebäude",
                            IsActive = true,
                            Latitude = 48.1351m,
                            Longitude = 11.5820m,
                            Name = "Hauptgebäude Parkplatz",
                            PostalCode = "80331",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Address = "Friedrichstraße 45",
                            City = "Berlin",
                            Country = "Deutschland",
                            CreatedAt = new DateTime(2025, 10, 8, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8346),
                            Description = "Ladepark an der Berliner Niederlassung",
                            IsActive = true,
                            Latitude = 52.5200m,
                            Longitude = 13.4050m,
                            Name = "Außenstelle Berlin",
                            PostalCode = "10117",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorizationMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChargingConnectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChargingStationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EnergyDelivered")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("OcppTransactionId")
                        .HasColumnType("int");

                    b.Property<Guid?>("QrCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationMethodId");

                    b.HasIndex("ChargingConnectorId");

                    b.HasIndex("ChargingStationId");

                    b.HasIndex("QrCodeId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ChargingSessions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChargeBoxId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ChargingParkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<int>("MaxPower")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumberOfConnectors")
                        .HasColumnType("int");

                    b.Property<string>("OcppEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OcppPassword")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OcppProtocol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChargingParkId");

                    b.HasIndex("StationId")
                        .IsUnique();

                    b.ToTable("ChargingStations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ChargingParkId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 10, 3, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8375),
                            IsActive = true,
                            LastHeartbeat = new DateTime(2025, 10, 23, 14, 51, 25, 351, DateTimeKind.Utc).AddTicks(8375),
                            Latitude = 48.1351m,
                            Longitude = 11.5820m,
                            MaxPower = 150,
                            Model = "Sicharge CC",
                            Name = "CCS Schnellladesäule 1",
                            NumberOfConnectors = 2,
                            StationId = "CCS-001",
                            Status = 0,
                            Type = 1,
                            Vendor = "Siemens"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            ChargingParkId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 10, 5, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8380),
                            IsActive = true,
                            LastHeartbeat = new DateTime(2025, 10, 23, 14, 53, 25, 351, DateTimeKind.Utc).AddTicks(8380),
                            Latitude = 48.1352m,
                            Longitude = 11.5821m,
                            MaxPower = 22,
                            Model = "Terra AC",
                            Name = "AC Standardladesäule 1",
                            NumberOfConnectors = 2,
                            StationId = "AC-001",
                            Status = 0,
                            Type = 0,
                            Vendor = "ABB"
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStationGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChargingParkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChargingParkId");

                    b.HasIndex("TenantId");

                    b.ToTable("ChargingStationGroups");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStationGroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChargingStationGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChargingStationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationGroupId");

                    b.HasIndex("ChargingStationId");

                    b.ToTable("ChargingStationGroupMemberships");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.GroupPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserGroupId", "PermissionId")
                        .IsUnique();

                    b.ToTable("GroupPermissions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5cd9d607-2900-465d-880f-0591d17dab70"),
                            Action = "view",
                            Description = "View users",
                            Name = "users.view",
                            Resource = "users"
                        },
                        new
                        {
                            Id = new Guid("7c161436-8436-472e-8630-b698f32c7f1b"),
                            Action = "create",
                            Description = "Create users",
                            Name = "users.create",
                            Resource = "users"
                        },
                        new
                        {
                            Id = new Guid("96b9b014-b140-41b7-8cfd-248780d5cec1"),
                            Action = "edit",
                            Description = "Edit users",
                            Name = "users.edit",
                            Resource = "users"
                        },
                        new
                        {
                            Id = new Guid("d535ad43-8c6a-45f8-8ac2-4c95a2cdfba5"),
                            Action = "delete",
                            Description = "Delete users",
                            Name = "users.delete",
                            Resource = "users"
                        },
                        new
                        {
                            Id = new Guid("84d5dc64-d276-4a58-b48a-f800860b6cf2"),
                            Action = "view",
                            Description = "View vehicles",
                            Name = "vehicles.view",
                            Resource = "vehicles"
                        },
                        new
                        {
                            Id = new Guid("c028445b-8bc8-4555-871b-618c98d6d69b"),
                            Action = "create",
                            Description = "Create vehicles",
                            Name = "vehicles.create",
                            Resource = "vehicles"
                        },
                        new
                        {
                            Id = new Guid("7e14b3fa-fa5c-42e9-8e42-816cb5a7d6aa"),
                            Action = "edit",
                            Description = "Edit vehicles",
                            Name = "vehicles.edit",
                            Resource = "vehicles"
                        },
                        new
                        {
                            Id = new Guid("560b1513-3720-429a-bcfc-374298a2b263"),
                            Action = "assign",
                            Description = "Assign vehicles",
                            Name = "vehicles.assign",
                            Resource = "vehicles"
                        },
                        new
                        {
                            Id = new Guid("1eb710e7-bbf3-4bf1-8f32-249c4655304d"),
                            Action = "view",
                            Description = "View charging infrastructure",
                            Name = "charging.view",
                            Resource = "charging"
                        },
                        new
                        {
                            Id = new Guid("1462baa9-f966-419b-9551-4c840d84b7a3"),
                            Action = "manage",
                            Description = "Manage charging infrastructure",
                            Name = "charging.manage",
                            Resource = "charging"
                        },
                        new
                        {
                            Id = new Guid("61b6872f-8e41-45f1-b6ab-a7e0ae8263ea"),
                            Action = "view",
                            Description = "View billing information",
                            Name = "billing.view",
                            Resource = "billing"
                        },
                        new
                        {
                            Id = new Guid("da09ab24-82de-4067-aaac-00e9371e6044"),
                            Action = "manage",
                            Description = "Manage billing",
                            Name = "billing.manage",
                            Resource = "billing"
                        },
                        new
                        {
                            Id = new Guid("adee50c8-57ab-44b1-9547-da2ef4f650ac"),
                            Action = "view",
                            Description = "View QR codes",
                            Name = "qrcodes.view",
                            Resource = "qrcodes"
                        },
                        new
                        {
                            Id = new Guid("0509bad7-8c59-42a0-837f-e1987ef19644"),
                            Action = "create",
                            Description = "Create QR codes",
                            Name = "qrcodes.create",
                            Resource = "qrcodes"
                        },
                        new
                        {
                            Id = new Guid("92e8640d-b0be-4823-af18-99c25a80eaaa"),
                            Action = "manage",
                            Description = "Manage QR codes",
                            Name = "qrcodes.manage",
                            Resource = "qrcodes"
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.QrCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChargingParkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentUses")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChargingParkId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("QrCodes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeee2222-2222-2222-2222-222222222222"),
                            ChargingParkId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Code = "CC-PARK-001",
                            CreatedAt = new DateTime(2025, 10, 13, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8544),
                            CurrentUses = 0,
                            Description = "Einladung zum Hauptparkplatz",
                            ExpiresAt = new DateTime(2026, 10, 23, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8543),
                            IsActive = true,
                            MaxUses = 100,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Type = 0
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Theme")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ParentTenantId");

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Musterstraße 123",
                            City = "Berlin",
                            Country = "Deutschland",
                            CreatedAt = new DateTime(2025, 9, 23, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8200),
                            Description = "Hauptunternehmen für Lade-Management",
                            Email = "info@chargingcontrol.de",
                            IsActive = true,
                            Name = "ChargingControl GmbH",
                            Phone = "+49 30 12345678",
                            PostalCode = "10115",
                            Subdomain = "chargingcontrol",
                            TaxId = "DE123456789",
                            Theme = 0,
                            Website = "https://www.chargingcontrol.de"
                        },
                        new
                        {
                            Id = new Guid("aaaabbbb-1111-2222-3333-444444444444"),
                            Address = "Acme Straße 456",
                            City = "München",
                            Country = "Deutschland",
                            CreatedAt = new DateTime(2025, 9, 28, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8209),
                            Description = "Sub-Tenant für Acme Corporation",
                            Email = "info@acme.de",
                            IsActive = true,
                            Name = "Acme GmbH",
                            ParentTenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Phone = "+49 89 98765432",
                            PostalCode = "80331",
                            Subdomain = "acme",
                            TaxId = "DE987654321",
                            Theme = 0,
                            Website = "https://www.acme.de"
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 9, 23, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8272),
                            Email = "admin@chargingcontrol.com",
                            FirstName = "Admin",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            LastLoginAt = new DateTime(2025, 10, 22, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8272),
                            LastName = "User",
                            PasswordHash = "$2a$11$QUxBZq94RgWvH09M.ER7EuF6Ju3mP45b9cEXAS99Iz09cAfKEZUeW",
                            Role = 1,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaabbbb-2222-3333-4444-555555555555"),
                            CreatedAt = new DateTime(2025, 9, 28, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8278),
                            Email = "admin@acme.com",
                            FirstName = "John",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            LastLoginAt = new DateTime(2025, 10, 21, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8278),
                            LastName = "Doe",
                            PasswordHash = "$2a$11$QUxBZq94RgWvH09M.ER7EuF6Ju3mP45b9cEXAS99Iz09cAfKEZUeW",
                            Role = 1,
                            TenantId = new Guid("aaaabbbb-1111-2222-3333-444444444444")
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InviteToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("InviteTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 9, 23, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8240),
                            Description = "Vollständige Administrator-Rechte",
                            IsActive = true,
                            Name = "Administratoren",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaabbbb-3333-4444-5555-666666666666"),
                            CreatedAt = new DateTime(2025, 9, 28, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8241),
                            Description = "Administrator-Rechte für Acme",
                            IsActive = true,
                            Name = "Acme Administratoren",
                            TenantId = new Guid("aaaabbbb-1111-2222-3333-444444444444")
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroupChargingStationGroupPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChargingStationGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChargingStationGroupId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("UserGroupChargingStationGroupPermissions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserGroupId");

                    b.HasIndex("UserId", "UserGroupId")
                        .IsUnique();

                    b.ToTable("UserGroupMemberships");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccccdddd-1111-2222-3333-444444444444"),
                            AssignedAt = new DateTime(2025, 9, 23, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8306),
                            UserGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("ccccdddd-2222-3333-4444-555555555555"),
                            AssignedAt = new DateTime(2025, 9, 28, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8309),
                            UserGroupId = new Guid("aaaabbbb-3333-4444-5555-666666666666"),
                            UserId = new Guid("aaaabbbb-2222-3333-4444-555555555555")
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "LicensePlate")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Color = "Pearl White",
                            CreatedAt = new DateTime(2025, 9, 28, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8443),
                            IsActive = true,
                            LicensePlate = "M-CC 1234",
                            Make = "Tesla",
                            Model = "Model 3",
                            Notes = "Poolfahrzeug für Geschäftsreisen",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Type = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Color = "Mineral White",
                            CreatedAt = new DateTime(2025, 10, 3, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8444),
                            IsActive = true,
                            LicensePlate = "M-CC 5678",
                            Make = "BMW",
                            Model = "i3",
                            Notes = "Dienstwagen für den Vertrieb",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Type = 1,
                            Year = 2022
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.VehicleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignmentType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleAssignments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccc0000-0000-0000-0000-000000000000"),
                            AssignedAt = new DateTime(2025, 10, 16, 14, 56, 25, 351, DateTimeKind.Utc).AddTicks(8477),
                            AssignmentType = 1,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            VehicleId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.AuthorizationMethod", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.User", "User")
                        .WithMany("AuthorizationMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.BillingAccount", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany("BillingAccounts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.BillingTransaction", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.BillingAccount", "BillingAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingSession", "ChargingSession")
                        .WithMany()
                        .HasForeignKey("ChargingSessionId");

                    b.Navigation("BillingAccount");

                    b.Navigation("ChargingSession");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingConnector", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingStation", "ChargingStation")
                        .WithMany("Connectors")
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingStation");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingPark", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany("ChargingParks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingSession", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.AuthorizationMethod", "AuthorizationMethod")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("AuthorizationMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingConnector", "ChargingConnector")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("ChargingConnectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingStation", null)
                        .WithMany("ChargingSessions")
                        .HasForeignKey("ChargingStationId");

                    b.HasOne("ChargingControlSystem.Data.Entities.QrCode", "QrCode")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("QrCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.User", "User")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChargingControlSystem.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AuthorizationMethod");

                    b.Navigation("ChargingConnector");

                    b.Navigation("QrCode");

                    b.Navigation("Tenant");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStation", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingPark", "ChargingPark")
                        .WithMany("ChargingStations")
                        .HasForeignKey("ChargingParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingPark");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStationGroup", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingPark", "ChargingPark")
                        .WithMany()
                        .HasForeignKey("ChargingParkId");

                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingPark");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStationGroupMembership", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingStationGroup", "ChargingStationGroup")
                        .WithMany("StationMemberships")
                        .HasForeignKey("ChargingStationGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingStation", "ChargingStation")
                        .WithMany()
                        .HasForeignKey("ChargingStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChargingStation");

                    b.Navigation("ChargingStationGroup");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.GroupPermission", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Permission", "Permission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.UserGroup", "UserGroup")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.QrCode", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingPark", "ChargingPark")
                        .WithMany("QrCodes")
                        .HasForeignKey("ChargingParkId");

                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.User", "User")
                        .WithMany("QrCodes")
                        .HasForeignKey("UserId");

                    b.Navigation("ChargingPark");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Tenant", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "ParentTenant")
                        .WithMany("SubTenants")
                        .HasForeignKey("ParentTenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.User", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroup", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.User", null)
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroupChargingStationGroupPermission", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.ChargingStationGroup", "ChargingStationGroup")
                        .WithMany("UserGroupPermissions")
                        .HasForeignKey("ChargingStationGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.UserGroup", "UserGroup")
                        .WithMany("ChargingStationGroupPermissions")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChargingStationGroup");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroupMembership", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.UserGroup", "UserGroup")
                        .WithMany("UserGroupMemberships")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.User", "User")
                        .WithMany("UserGroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Vehicle", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.Tenant", "Tenant")
                        .WithMany("Vehicles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.VehicleAssignment", b =>
                {
                    b.HasOne("ChargingControlSystem.Data.Entities.User", "User")
                        .WithMany("VehicleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChargingControlSystem.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleAssignments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.AuthorizationMethod", b =>
                {
                    b.Navigation("ChargingSessions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.BillingAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingConnector", b =>
                {
                    b.Navigation("ChargingSessions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingPark", b =>
                {
                    b.Navigation("ChargingStations");

                    b.Navigation("QrCodes");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStation", b =>
                {
                    b.Navigation("ChargingSessions");

                    b.Navigation("Connectors");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.ChargingStationGroup", b =>
                {
                    b.Navigation("StationMemberships");

                    b.Navigation("UserGroupPermissions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Permission", b =>
                {
                    b.Navigation("GroupPermissions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.QrCode", b =>
                {
                    b.Navigation("ChargingSessions");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Tenant", b =>
                {
                    b.Navigation("BillingAccounts");

                    b.Navigation("ChargingParks");

                    b.Navigation("ChargingSessions");

                    b.Navigation("SubTenants");

                    b.Navigation("Users");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.User", b =>
                {
                    b.Navigation("AuthorizationMethods");

                    b.Navigation("ChargingSessions");

                    b.Navigation("QrCodes");

                    b.Navigation("UserGroupMemberships");

                    b.Navigation("UserGroups");

                    b.Navigation("VehicleAssignments");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.UserGroup", b =>
                {
                    b.Navigation("ChargingStationGroupPermissions");

                    b.Navigation("GroupPermissions");

                    b.Navigation("UserGroupMemberships");
                });

            modelBuilder.Entity("ChargingControlSystem.Data.Entities.Vehicle", b =>
                {
                    b.Navigation("ChargingSessions");

                    b.Navigation("VehicleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
